#!/bin/bash

#free_memory: prints out free memory
#used_memory: prints out used memory
#av_memory: prints out total available memory
#free_space: prints out unused disk space on primary hard drive
#used_space: prints out used disk space on primary hard drive
#av_space: prints out total available disk space on primary hard drive


free_memory (){
    
    free -h | head -2 | tail -1 | awk '{print $4}'
}

used_memory(){
    free -h | head -2 | tail -1 | awk '{print $3}'
}

av_memory(){
    free -h | head -2 | tail -1 | awk '{print $2}'
}

free_space(){
	df -h / | head -2 | tail -1 | awk '{print $4}'
}

used_space(){
	df -h / | head -2 | tail -1 | awk '{print $3}'
}	

av_space(){
	df -h / | head -2 | tail -1 | awk '{print $2}'
}

percent_space_used(){
    df -h / | head -2 | tail -1 | awk '{print $5}' | cut -d'%' -f1
    
}
